
---
-   hosts: 127.0.0.1
    connection: local
    become: yes
    remote_user: root
    vars:
        web_application_access_port: '5000'
        init_free5gc_elements_simulation: 'true'
        start_webapp: 'true'
        deploy_oaisim: 'true'
        deploy_free5gc: 'true'
        force_docker_reinstall: 'false'
        init_enb: 'true'
        init_ue: 'true'
        num_ues_init_simulation: '3'
        docker_custom_subnet_network: '192.172.2.0/24'
        docker_custom_network_name: '5g_Dep'
        BASE_DIR_INSTALL: '/root/oaisim-free5g-install'
        ip_address_AMF: '192.172.2.2'
        ip_address_SMF: '192.172.2.3'
        ip_address_HSS: '192.172.2.4'
        ip_address_PCRF: '192.172.2.5'
        ip_address_UPF: '192.172.2.6'
        ip_address_MONGO_DB: '192.172.2.100'
        ip_address_WEB_UI: '192.172.2.101'
        ip_address_OAISIM_ENB: '192.172.2.253'
        ip_address_OAISIM_UE: '192.172.2.254'
        free5gc_st1_image_name: 'laboraufg/free5gc-st1'
        free5gc_webui_image_name: 'laboraufg/webui-free5gc'
        free5gc_mongodb_image_name: 'laboraufg/mongodb-free5gc'
        oaisim_enb_image_name: 'laboraufg/enb-openairsim'
        oaisim_ue_image_name: 'laboraufg/ue-openairsim'
        UE_container_name: 'ue'
        UE_folder_name_container_name: '/root/ue/'
        ENB_folder_name_container_name: '/root/enb/'
        ENB_container_name: 'enb'
        AMF_container_name: 'amf'
        UPF_container_name: 'upf'
        SMF_container_name: 'smf'
        HSS_container_name: 'hss'
        PCRF_container_name: 'pcrf'
        MONGO_DB_container_name: 'mongodb-svc'
        WEB_UI_container_name: 'webui'
        clear_file_instalation: 'true'
        HPLMN : "30234"
        default_username_WEBUI : "admin"
        default_password_WEBUI : "1423"
        enb_gumei_mcc_auth_param: '302'
        enb_gumei_mnc_auth_param: '34'
        log_level_tracer_free5gc: '5'
        path_workspace_free5gc: '/root/free5gc-stage-1'
        USIM_API_K : "8baf473f2f8fd09487cccbd7097c6862"
        OPC : "e734f8734007d6c5ce7a0508809e7e9c"
        user_equiments:
            - { ue_id: UE0 ,   msin: '0000000001' }
            - { ue_id: UE1 ,   msin: '0000000002' }
            - { ue_id: UE2 ,   msin: '0000000003' }
    tasks:
        - name: Environment validation!
          assert:
            that:
              - ansible_memtotal_mb >= 3500
            msg: "Minimum memory requirements in the deployment environment is 4GB! Operation failed!"

        - fail: 
            msg: "'USIM_API_K' value cannot be different of of 8baf473f2f8fd09487cccbd7097c6862"
          when: USIM_API_K != '8baf473f2f8fd09487cccbd7097c6862'

        - fail: 
            msg: "It's not possible INIT_UE whitout INIT_ENB, plese set init_enb='true' and try again!"
          when: init_ue == 'true'  and init_enb == 'false'

        - fail: 
            msg: "'OPC' value cannot be different of of e734f8734007d6c5ce7a0508809e7e9c"
          when: OPC != 'e734f8734007d6c5ce7a0508809e7e9c'

        - fail: 
            msg: "'HPLMN' value cannot be different of of 30234"
          when: HPLMN != '30234'

        - fail: 
            msg: "'internet_network_interface' not found, this parameter is required!"
          when: internet_network_interface == ''
          
        - name  : Remove old instalation
          shell :  |
                sudo rm -rf {{ BASE_DIR_INSTALL }}
                
        - name  : Remove docker installation
          shell :  |
                sudo apt autoremove -y --purge docker-engine docker docker.io docker-ce 
                sudo apt update
          when: force_docker_reinstall == 'true'
        
        - name  : Install Basic requirements
          apt   :
                name: ['openssh-client', 'net-tools', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common', 'python-setuptools', 'python3-pip']
                state: present
                update_cache: yes
                
        - name  : Create dir instalation
          shell :  |
                mkdir {{ BASE_DIR_INSTALL }}
        
        - name  : Build iptables_upf.sh file
          copy  :
            dest: "{{ BASE_DIR_INSTALL }}/iptables_upf.sh"
            content: |
                #!/bin/bash

                iptables -C FORWARD -i uptun -o eth0 -j ACCEPT
                output=$?
                if [ $output -eq 1 ]; then
                    echo "Masquerade..."
                    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
                    echo "Conntrack..."
                    iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
                    echo "Uptun..."
                    iptables -A FORWARD -i uptun -o eth0 -j ACCEPT
                fi
          when  : deploy_free5gc == 'true'

        - name  : Build setup_upf.sh file
          copy  :
            dest: "{{ BASE_DIR_INSTALL }}/setup_upf.sh"
            content: |
                #!/bin/sh

                if ! grep "uptun" /proc/net/dev > /dev/null; then
                    ip tuntap add name uptun mode tun
                fi
                ip addr del 45.45.0.1/16 dev uptun 2> /dev/null
                ip addr add 45.45.0.1/16 dev uptun
                ip addr del cafe::1/64 dev uptun 2> /dev/null
                ip addr add cafe::1/64 dev uptun
                ip link set uptun up
          when  : deploy_free5gc == 'true'

        - name  : Core Network Configuration - Build free5gc.conf
          copy:
            dest: "{{ BASE_DIR_INSTALL }}/free5gc.conf"
            content: |
              db_uri: mongodb://mongodb-svc/free5gc
              logger:
                  file: {{ path_workspace_free5gc }}/install/var/log/free5gc/free5gc.log
                  trace: 
                      app: {{ log_level_tracer_free5gc }}
                      s1ap: {{ log_level_tracer_free5gc }}
                      nas: {{ log_level_tracer_free5gc }}
                      diameter: {{ log_level_tracer_free5gc }}
                      gtp: {{ log_level_tracer_free5gc }}
                      pfcp: {{ log_level_tracer_free5gc }}
                      sbi: {{ log_level_tracer_free5gc }}
              
              parameter:
                  no_ipv6: true
              amf:
                  freeDiameter: amf.conf
              
                  s1ap:
                    addr: {{ ip_address_AMF }}
              
                  gummei: 
                    plmn_id:
                      mcc: {{ enb_gumei_mcc_auth_param }}
                      mnc: {{ enb_gumei_mnc_auth_param }}
                    mme_gid: 1
                    mme_code: 1
              
                  tai:
                    plmn_id:
                      mcc: {{ enb_gumei_mcc_auth_param }}
                      mnc: {{ enb_gumei_mnc_auth_param }}
                    tac: 1
                  security:
                      integrity_order : [ EIA1, EIA2, EIA0 ]
                      ciphering_order : [ EEA0, EEA1, EEA2 ]
              
                  network_name:
                      full: free5GC
              hss:
                  freeDiameter: hss.conf
              pcrf:
                  freeDiameter: pcrf.conf
              smf:
                  freeDiameter: smf.conf
                  pfcp:
                    - addr: {{ ip_address_SMF }}
                  upf:
                    - addr: {{ ip_address_UPF }}
                  http:
                    addr: {{ ip_address_SMF }}
                    port: 8080
              
                  ue_pool:
                    - addr: 45.45.0.1/16
              
                  dns:
                    - 8.8.8.8
                    - 8.8.4.4
              upf:
                  pfcp:
                    addr:
                      - {{ ip_address_UPF }}
              
                  gtpu:
                    - addr: {{ ip_address_UPF }}
                  ue_pool:
                    - addr: 45.45.0.1/16
                  dns:
                    - 8.8.8.8
                    - 8.8.4.4
          when  : deploy_free5gc == 'true'

        - name  : Core Network Configuration - Build amf.conf
          copy:
            dest: "{{ BASE_DIR_INSTALL }}/amf.conf"
            content: |
              Identity = "amf.localdomain";
              Realm = "localdomain";
              No_SCTP;
              ListenOn = "{{ ip_address_AMF }}";
              TLS_Cred = "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/amf.cert.pem", "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/amf.key.pem";
              TLS_CA = "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/cacert.pem";
              LoadExtension = "dbg_msg_dumps.so" : "0x8888";
              LoadExtension = "dict_rfc5777.so";
              LoadExtension = "dict_mip6i.so";
              LoadExtension = "dict_nasreq.so";
              LoadExtension = "dict_nas_mipv6.so";
              LoadExtension = "dict_dcca.so";
              LoadExtension = "dict_dcca_3gpp.so";
              LoadExtension = "dict_s6a.so";
              ConnectPeer = "hss.localdomain" { ConnectTo = "{{ ip_address_HSS }}"; No_TLS; };
          when  : deploy_free5gc == 'true'

        - name  : Core Network Configuration - Build smf.conf
          copy:
            dest: "{{ BASE_DIR_INSTALL }}/smf.conf"
            content: |
              Identity = "smf.localdomain";
              Realm = "localdomain";
              No_SCTP;
              ListenOn = "{{ ip_address_SMF }}";
              TLS_Cred = "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/smf.cert.pem", "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/smf.key.pem";
              TLS_CA = "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/cacert.pem";
              LoadExtension = "dbg_msg_dumps.so" : "0x8888";
              LoadExtension = "dict_rfc5777.so";
              LoadExtension = "dict_mip6i.so";
              LoadExtension = "dict_nasreq.so";
              LoadExtension = "dict_nas_mipv6.so";
              LoadExtension = "dict_dcca.so";
              LoadExtension = "dict_dcca_3gpp.so";
              ConnectPeer = "pcrf.localdomain" { ConnectTo = "{{ ip_address_PCRF }}"; No_TLS; };
          when  : deploy_free5gc == 'true'

        - name  : Core Network Configuration - Build hss.conf
          copy:
            dest: "{{ BASE_DIR_INSTALL }}/hss.conf"
            content: |
                Identity = "hss.localdomain";
                Realm = "localdomain";
                No_SCTP;
                ListenOn = "{{ ip_address_HSS }}";
                TLS_Cred = "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/hss.cert.pem", "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/hss.key.pem";
                TLS_CA = "{{ path_workspace_free5gc }}/install/etc/free5gc/freeDiameter/cacert.pem";
                
                LoadExtension = "dbg_msg_dumps.so" : "0x8888";
                LoadExtension = "dict_rfc5777.so";
                LoadExtension = "dict_mip6i.so";
                LoadExtension = "dict_nasreq.so";
                LoadExtension = "dict_nas_mipv6.so";
                LoadExtension = "dict_dcca.so";
                LoadExtension = "dict_dcca_3gpp.so";
                LoadExtension = "dict_s6a.so";
                ConnectPeer = "amf.localdomain" { ConnectTo = "{{ ip_address_AMF }}"; No_TLS; };
          when  : deploy_free5gc == 'true'
